%% Principal component analysis

%% Initialization
clear;
load('digits');

%% Subtract out the mean image from each column of X
mean = sum(X, 2) / size(X, 2);
Xbar = X - repmat(mean, 1, size(X, 2));

%% Minimize the approximation error ||Xbar - VY||
% We have to project the vectors (columns of Xbar) on the subspace of
% dimension k generated by the eigenvectors associated with the k
% biggest eigenvalues of the covariance matrix.

k = 25;

S = cov(X');

% compute the k largest magnitude of S ude eigenvalues and the matrix V of
% eigenvectors
[V, ~] = eigs(S, k);

% choose the eigenvector to be on the unit-sphere
normc(V);

%% Projection matrix on the subspace of dim k
% Should be V * inv(V' * V) * V' but as the column of V are an orthonormal
% basis, V' * V = I
P = V * V';

%% Project the image on the subset and add back the mean
Y = P * Xbar + repmat(mean, 1, size(X, 2));

%% Display the images
displayImage(V);